version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - common_network

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    networks:
      - common_network

  nats:
    image: nats
    ports:
      - "4222:4222"
    networks:
      - common_network

  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    networks:
      - common_network

networks:
  common_network:

